{ "formStruct" : {
   "fields": {
      "prop_info>Slug": {
         "name": "prop_info>Slug",
         "label": "Slug",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Updated_at": {
         "name": "prop_info>Updated_at",
         "label": "Updated at",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Created_at": {
         "name": "prop_info>Created_at",
         "label": "Created at",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Industry": {
         "name": "prop_info>Industry",
         "label": "Industry",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>ID": {
         "name": "prop_info>ID",
         "label": "ID",
         "type": "INTEGER",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Name": {
         "name": "prop_info>Name",
         "label": "Name",
         "type": "VARCHAR(200)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Grade": {
         "name": "prop_info>Grade",
         "label": "Grade",
         "type": "ENUM(50)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Country": {
         "name": "prop_info>Country",
         "label": "Country",
         "type": "ENUM(50)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>PostalCode": {
         "name": "prop_info>PostalCode",
         "label": "PostalCode",
         "type": "int",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Street_no": {
         "name": "prop_info>Street_no",
         "label": "Street no",
         "type": "VARCHAR(10)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Street": {
         "name": "prop_info>Street",
         "label": "Street",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Address": {
         "name": "prop_info>Address",
         "label": "Address",
         "type": "VARCHAR(200)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Property_type": {
         "name": "prop_info>Property_type",
         "label": "Property type",
         "type": "VARCHAR(300)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Region": {
         "name": "prop_info>Region",
         "label": "Region",
         "type": "ENUM(50)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Micromarket": {
         "name": "prop_info>Micromarket",
         "label": "Micromarket",
         "type": "ENUM(50)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Zoning": {
         "name": "prop_info>Zoning",
         "label": "Zoning",
         "type": "ENUM(50)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Property_Usage": {
         "name": "prop_info>Property_Usage",
         "label": "Property Usage",
         "type": "ENUM(50)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>LandOwnership": {
         "name": "prop_info>LandOwnership",
         "label": "LandOwnership",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>OwnershipStructure_Title": {
         "name": "prop_info>OwnershipStructure_Title",
         "label": "OwnershipStructure Title",
         "type": "ENUM(50)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>PropertyStatus": {
         "name": "prop_info>PropertyStatus",
         "label": "PropertyStatus",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>TOPDate": {
         "name": "prop_info>TOPDate",
         "label": "TOPDate",
         "type": "datetime",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>GrossFloorArea": {
         "name": "prop_info>GrossFloorArea",
         "label": "GrossFloorArea",
         "type": "decimal(12,2)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>LandArea": {
         "name": "prop_info>LandArea",
         "label": "LandArea",
         "type": "decimal(12,2)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>NetLettableArea": {
         "name": "prop_info>NetLettableArea",
         "label": "NetLettableArea",
         "type": "decimal(12,2)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>AreaBreakdown": {
         "name": "prop_info>AreaBreakdown",
         "label": "AreaBreakdown",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Headline": {
         "name": "prop_info>Headline",
         "label": "Headline",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>LocationDescription": {
         "name": "prop_info>LocationDescription",
         "label": "LocationDescription",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>BuildingDescription": {
         "name": "prop_info>BuildingDescription",
         "label": "BuildingDescription",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>BelowGround": {
         "name": "prop_info>BelowGround",
         "label": "BelowGround",
         "type": "int",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>AboveGround": {
         "name": "prop_info>AboveGround",
         "label": "AboveGround",
         "type": "int",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>TotalFloors": {
         "name": "prop_info>TotalFloors",
         "label": "TotalFloors",
         "type": "int",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Tenant": {
         "name": "prop_info>Tenant",
         "label": "Tenant",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>WithinComplex": {
         "name": "prop_info>WithinComplex",
         "label": "WithinComplex",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>WithinProximity": {
         "name": "prop_info>WithinProximity",
         "label": "WithinProximity",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Public": {
         "name": "prop_info>Public",
         "label": "Public",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Private": {
         "name": "prop_info>Private",
         "label": "Private",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>NoofPassengerLift": {
         "name": "prop_info>NoofPassengerLift",
         "label": "NoofPassengerLift",
         "type": "int",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>CarParkLifttoG_F": {
         "name": "prop_info>CarParkLifttoG_F",
         "label": "CarParkLifttoG F",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>ServiceLift": {
         "name": "prop_info>ServiceLift",
         "label": "ServiceLift",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>CargoLift": {
         "name": "prop_info>CargoLift",
         "label": "CargoLift",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>NoofLiftZone": {
         "name": "prop_info>NoofLiftZone",
         "label": "NoofLiftZone",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>CarParkLots": {
         "name": "prop_info>CarParkLots",
         "label": "CarParkLots",
         "type": "int",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>AllocationRatio": {
         "name": "prop_info>AllocationRatio",
         "label": "AllocationRatio",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>UOM_AllocationRatio": {
         "name": "prop_info>UOM_AllocationRatio",
         "label": "UOM AllocationRatio",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>ParkingDetails": {
         "name": "prop_info>ParkingDetails",
         "label": "ParkingDetails",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Seasonal": {
         "name": "prop_info>Seasonal",
         "label": "Seasonal",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Non_Reserved": {
         "name": "prop_info>Non_Reserved",
         "label": "Non Reserved",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>MRT1": {
         "name": "prop_info>MRT1",
         "label": "MRT1",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>MRT1CoveredAccess": {
         "name": "prop_info>MRT1CoveredAccess",
         "label": "MRT1CoveredAccess",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>MRT1Walk_Drive": {
         "name": "prop_info>MRT1Walk_Drive",
         "label": "MRT1Walk Drive",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>MRT1Time_Mins": {
         "name": "prop_info>MRT1Time_Mins",
         "label": "MRT1Time Mins",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>MRT2": {
         "name": "prop_info>MRT2",
         "label": "MRT2",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>MRT2CoveredAccess": {
         "name": "prop_info>MRT2CoveredAccess",
         "label": "MRT2CoveredAccess",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>MRT2Walk_Drive": {
         "name": "prop_info>MRT2Walk_Drive",
         "label": "MRT2Walk Drive",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>MRT2Time_Mins_": {
         "name": "prop_info>MRT2Time_Mins_",
         "label": "MRT2Time Mins ",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>MRT3": {
         "name": "prop_info>MRT3",
         "label": "MRT3",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>MRT3CoveredAccess": {
         "name": "prop_info>MRT3CoveredAccess",
         "label": "MRT3CoveredAccess",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>MRT3Walk_Drive": {
         "name": "prop_info>MRT3Walk_Drive",
         "label": "MRT3Walk Drive",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>MRT3Time_Mins": {
         "name": "prop_info>MRT3Time_Mins",
         "label": "MRT3Time Mins",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Bus": {
         "name": "prop_info>Bus",
         "label": "Bus",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Others": {
         "name": "prop_info>Others",
         "label": "Others",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>FloorToCeilingHeight_From": {
         "name": "prop_info>FloorToCeilingHeight_From",
         "label": "FloorToCeilingHeight From",
         "type": "decimal(12,2)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>FloorToCeilingHeight_To": {
         "name": "prop_info>FloorToCeilingHeight_To",
         "label": "FloorToCeilingHeight To",
         "type": "decimal(12,2)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>FloorLoadingRange_From": {
         "name": "prop_info>FloorLoadingRange_From",
         "label": "FloorLoadingRange From",
         "type": "decimal(12,2)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>FloorLoadingRange_To": {
         "name": "prop_info>FloorLoadingRange_To",
         "label": "FloorLoadingRange To",
         "type": "decimal(12,2)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>CeilingGrid_FloorLoadingDetails": {
         "name": "prop_info>CeilingGrid_FloorLoadingDetails",
         "label": "CeilingGrid FloorLoadingDetails",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>FloorSystem": {
         "name": "prop_info>FloorSystem",
         "label": "FloorSystem",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>PowerSystem": {
         "name": "prop_info>PowerSystem",
         "label": "PowerSystem",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>NoOfOfficeFloors": {
         "name": "prop_info>NoOfOfficeFloors",
         "label": "NoOfOfficeFloors",
         "type": "decimal(12,2)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>TypicalMinimumFloorSize": {
         "name": "prop_info>TypicalMinimumFloorSize",
         "label": "TypicalMinimumFloorSize",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>MaximumFloorSize_SqFt": {
         "name": "prop_info>MaximumFloorSize_SqFt",
         "label": "MaximumFloorSize SqFt",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>UltraHigh_TopFloor": {
         "name": "prop_info>UltraHigh_TopFloor",
         "label": "UltraHigh TopFloor",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>High_TopFloor": {
         "name": "prop_info>High_TopFloor",
         "label": "High TopFloor",
         "type": "ENUM(50)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Mid_TopFloor": {
         "name": "prop_info>Mid_TopFloor",
         "label": "Mid TopFloor",
         "type": "ENUM(50)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Low_TopFloor": {
         "name": "prop_info>Low_TopFloor",
         "label": "Low TopFloor",
         "type": "ENUM(50)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>TypeOfUse": {
         "name": "prop_info>TypeOfUse",
         "label": "TypeOfUse",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>NoOfLoadingBays": {
         "name": "prop_info>NoOfLoadingBays",
         "label": "NoOfLoadingBays",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>AccessibleFor": {
         "name": "prop_info>AccessibleFor",
         "label": "AccessibleFor",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Loading_UnloadingBay": {
         "name": "prop_info>Loading_UnloadingBay",
         "label": "Loading UnloadingBay",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>NoOfCranes": {
         "name": "prop_info>NoOfCranes",
         "label": "NoOfCranes",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>OtherDetails": {
         "name": "prop_info>OtherDetails",
         "label": "OtherDetails",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>NoOfRetailFloors": {
         "name": "prop_info>NoOfRetailFloors",
         "label": "NoOfRetailFloors",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>Kind": {
         "name": "prop_info>Kind",
         "label": "Kind",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "prop_info>AccountName": {
         "name": "prop_info>AccountName",
         "label": "AccountName",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      }
   },
   "lists": {
      "space_info": {
         "label": "space info",
         "fields": [
            {
               "name": "space_info>InfoUpdateBy",
               "label": "space info InfoUpdateBy",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "space_info>SpaceUsage",
               "label": "space info SpaceUsage",
               "type": "ENUM(50)",
               "inherit": ""
            },
            {
               "name": "space_info>Status",
               "label": "space info Status",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "space_info>MonthlyRentalFrom",
               "label": "space info MonthlyRentalFrom",
               "type": "decimal(12,2)",
               "inherit": ""
            },
            {
               "name": "space_info>Availability",
               "label": "space info Availability",
               "type": "ENUM(50)",
               "inherit": ""
            },
            {
               "name": "space_info>PropertyType",
               "label": "space info PropertyType",
               "type": "ENUM(50)",
               "inherit": ""
            },
            {
               "name": "space_info>SpaceID",
               "label": "space info SpaceID",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "space_info>SpaceCondition",
               "label": "space info SpaceCondition",
               "type": "ENUM(50)",
               "inherit": ""
            },
            {
               "name": "space_info>ID",
               "label": "space info ID",
               "type": "INTEGER",
               "inherit": ""
            },
            {
               "name": "space_info>Property_ID_x",
               "label": "space info Property ID x",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "space_info>BuildingName_x",
               "label": "space info BuildingName x",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "space_info>FloorID",
               "label": "space info FloorID",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "space_info>Floor",
               "label": "space info Floor",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "space_info>SortOrder",
               "label": "space info SortOrder",
               "type": "int",
               "inherit": ""
            },
            {
               "name": "space_info>SpaceName",
               "label": "space info SpaceName",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "space_info>Availability_SpaceStatus",
               "label": "space info Availability SpaceStatus",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "space_info>PossessionStatus",
               "label": "space info PossessionStatus",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "space_info>QuotedArea",
               "label": "space info QuotedArea",
               "type": "decimal(12,2)",
               "inherit": ""
            },
            {
               "name": "space_info>InfoUpdateDate",
               "label": "space info InfoUpdateDate",
               "type": "datetime",
               "inherit": ""
            },
            {
               "name": "space_info>CreatedBy",
               "label": "space info CreatedBy",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "space_info>ModifiedBy",
               "label": "space info ModifiedBy",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "space_info>AskingRentFrom",
               "label": "space info AskingRentFrom",
               "type": "decimal(12,2)",
               "inherit": ""
            },
            {
               "name": "space_info>AskingRentTo",
               "label": "space info AskingRentTo",
               "type": "decimal(12,2)",
               "inherit": ""
            },
            {
               "name": "space_info>MonthlyRentalTo",
               "label": "space info MonthlyRentalTo",
               "type": "decimal(12,2)",
               "inherit": ""
            },
            {
               "name": "space_info>Created_At",
               "label": "space info Created At",
               "type": "datetime",
               "inherit": ""
            },
            {
               "name": "space_info>Updated_At",
               "label": "space info Updated At",
               "type": "datetime",
               "inherit": ""
            },
            {
               "name": "po_floor_3D>floorplan_url",
               "label": "po floor 3D floorplan url",
               "type": "int",
               "inherit": "> (po_floor_3D,space_info,po_floor_3D_space_info) "
            },
            {
               "name": "po_floor_3D>Floor_id",
               "label": "po floor 3D Floor id",
               "type": "VARCHAR(20)",
               "inherit": "> (po_floor_3D,space_info,po_floor_3D_space_info) "
            }
         ]
      },
      "po_property_3D": {
         "label": "po property 3D",
         "fields": [
            {
               "name": "po_property_3D>Floor_id",
               "label": "po property 3D Floor id",
               "type": "VARCHAR(20)",
               "inherit": ""
            },
            {
               "name": "po_property_3D>ID",
               "label": "po property 3D ID",
               "type": "INTEGER",
               "inherit": ""
            },
            {
               "name": "po_property_3D>image_url",
               "label": "po property 3D image url",
               "type": "VARCHAR(200)",
               "inherit": ""
            },
            {
               "name": "po_property_3D>floorplan_url",
               "label": "po property 3D floorplan url",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "po_property_3D>asset_class",
               "label": "po property 3D asset class",
               "type": "ENUM(50)",
               "inherit": ""
            },
            {
               "name": "po_property_3D>available_units",
               "label": "po property 3D available units",
               "type": "ENUM(50)",
               "inherit": ""
            }
         ]
      },
      "shortlist": {
         "label": "shortlist",
         "fields": [
            {
               "name": "shortlist>share_with",
               "label": "shortlist share with",
               "type": "VARCHAR(500)",
               "inherit": ""
            },
            {
               "name": "shortlist>added_dt",
               "label": "shortlist added dt",
               "type": "datetime",
               "inherit": ""
            },
            {
               "name": "shortlist>user_id",
               "label": "shortlist user id",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "shortlist>Customer_name",
               "label": "shortlist Customer name",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "shortlist>Opportunityname",
               "label": "shortlist Opportunityname",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "shortlist>name",
               "label": "shortlist name",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "shortlist>ID",
               "label": "shortlist ID",
               "type": "INTEGER",
               "inherit": ""
            },
            {
               "name": "shortlist>available_units",
               "label": "shortlist available units",
               "type": "ENUM(50)",
               "inherit": ""
            }
         ]
      },
      "travel_time": {
         "label": "travel time",
         "fields": [
            {
               "name": "  travel_time>dest_type",
               "label": "  travel time dest type",
               "type": "ENUM(50)",
               "inherit": ""
            },
            {
               "name": "travel_time>dest_name",
               "label": "travel time dest name",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "travel_time>using",
               "label": "travel time using",
               "type": "ENUM(50)",
               "inherit": ""
            },
            {
               "name": "travel_time>km",
               "label": "travel time km",
               "type": "int",
               "inherit": ""
            },
            {
               "name": "travel_time>min",
               "label": "travel time min",
               "type": "int",
               "inherit": ""
            },
            {
               "name": "travel_time>action_c",
               "label": "travel time action c",
               "type": "int",
               "inherit": ""
            },
            {
               "name": "travel_time>ID",
               "label": "travel time ID",
               "type": "INTEGER",
               "inherit": ""
            }
         ]
      }
   },
   "entity": "prop_info"
},
 "sampleDataList" : {
   "Slug": "dummy_3",
   "Updated_at": "dummy_1",
   "Created_at": "dummy_6",
   "Industry": "dummy_9",
   "ID": 2,
   "Name": "dummy_5",
   "Grade": "poor",
   "Country": "Malaysia",
   "PostalCode": "dummy_0",
   "Street_no": "dummy_7",
   "Street": "dummy_2",
   "Address": "dummy_8",
   "Property_type": "dummy_6",
   "Region": "West",
   "Micromarket": "Bugis",
   "Zoning": "Business 2",
   "Property_Usage": "Commercial",
   "LandOwnership": "dummy_3",
   "OwnershipStructure_Title": "Leasehold",
   "PropertyStatus": "dummy_3",
   "TOPDate": "4/21/2022, 16:02:56",
   "GrossFloorArea": 9.45,
   "LandArea": 5.68,
   "NetLettableArea": 2,
   "AreaBreakdown": "dummy_0",
   "Headline": "dummy_0",
   "LocationDescription": "dummy_2",
   "BuildingDescription": "dummy_6",
   "BelowGround": "dummy_8",
   "AboveGround": "dummy_4",
   "TotalFloors": "dummy_1",
   "Tenant": "dummy_0",
   "WithinComplex": "dummy_1",
   "WithinProximity": "dummy_6",
   "Public": "dummy_1",
   "Private": "dummy_2",
   "NoofPassengerLift": "dummy_0",
   "CarParkLifttoG_F": "dummy_0",
   "ServiceLift": "dummy_9",
   "CargoLift": "dummy_2",
   "NoofLiftZone": "dummy_0",
   "CarParkLots": "dummy_5",
   "AllocationRatio": "dummy_3",
   "UOM_AllocationRatio": "dummy_1",
   "ParkingDetails": "dummy_1",
   "Seasonal": "dummy_0",
   "Non_Reserved": "dummy_3",
   "MRT1": "dummy_7",
   "MRT1CoveredAccess": "dummy_3",
   "MRT1Walk_Drive": "dummy_7",
   "MRT1Time_Mins": "dummy_1",
   "MRT2": "dummy_2",
   "MRT2CoveredAccess": "dummy_6",
   "MRT2Walk_Drive": "dummy_8",
   "MRT2Time_Mins_": "dummy_3",
   "MRT3": "dummy_4",
   "MRT3CoveredAccess": "dummy_0",
   "MRT3Walk_Drive": "dummy_1",
   "MRT3Time_Mins": "dummy_2",
   "Bus": "dummy_4",
   "Others": "dummy_9",
   "FloorToCeilingHeight_From": 9.16,
   "FloorToCeilingHeight_To": 9.45,
   "FloorLoadingRange_From": 5.88,
   "FloorLoadingRange_To": 4.37,
   "CeilingGrid_FloorLoadingDetails": "dummy_5",
   "FloorSystem": "dummy_9",
   "PowerSystem": "dummy_1",
   "NoOfOfficeFloors": 2.06,
   "TypicalMinimumFloorSize": "dummy_4",
   "MaximumFloorSize_SqFt": "dummy_9",
   "UltraHigh_TopFloor": "dummy_8",
   "High_TopFloor": "yes",
   "Mid_TopFloor": "no",
   "Low_TopFloor": "no",
   "TypeOfUse": "dummy_4",
   "NoOfLoadingBays": "dummy_4",
   "AccessibleFor": "dummy_0",
   "Loading_UnloadingBay": "dummy_4",
   "NoOfCranes": "dummy_8",
   "OtherDetails": "dummy_9",
   "NoOfRetailFloors": "dummy_5",
   "Kind": "dummy_2",
   "AccountName": "dummy_2",
   "lists": {
      "space_info": [
         {
            "InfoUpdateBy": "dummy_9",
            "SpaceUsage": "comercial",
            "Status": "dummy_5",
            "MonthlyRentalFrom": 2.93,
            "Availability": "yes",
            "PropertyType": "comercial",
            "SpaceID": "dummy_1",
            "SpaceCondition": "excelent",
            "ID": 6,
            "Property_ID_x": "dummy_9",
            "BuildingName_x": "dummy_2",
            "FloorID": "dummy_7",
            "Floor": "dummy_0",
            "SortOrder": "dummy_6",
            "SpaceName": "dummy_5",
            "Availability_SpaceStatus": "dummy_0",
            "PossessionStatus": "dummy_5",
            "QuotedArea": 6.21,
            "InfoUpdateDate": "1/4/2015, 23:36:26",
            "CreatedBy": "dummy_0",
            "ModifiedBy": "dummy_5",
            "AskingRentFrom": 6.35,
            "AskingRentTo": 4.61,
            "MonthlyRentalTo": 4.91,
            "Created_At": "12/27/2017, 15:31:59",
            "Updated_At": "8/7/2022, 20:24:54",
            "floorplan_url": "dummy_0",
            "Floor_id": "dummy_1"
         },
         {
            "InfoUpdateBy": "dummy_9",
            "SpaceUsage": "industrial",
            "Status": "dummy_6",
            "MonthlyRentalFrom": 1.21,
            "Availability": "no",
            "PropertyType": "industrial",
            "SpaceID": "dummy_7",
            "SpaceCondition": "average",
            "ID": 3,
            "Property_ID_x": "dummy_5",
            "BuildingName_x": "dummy_6",
            "FloorID": "dummy_7",
            "Floor": "dummy_7",
            "SortOrder": "dummy_6",
            "SpaceName": "dummy_8",
            "Availability_SpaceStatus": "dummy_6",
            "PossessionStatus": "dummy_6",
            "QuotedArea": 1.19,
            "InfoUpdateDate": "7/6/2015, 10:11:40",
            "CreatedBy": "dummy_5",
            "ModifiedBy": "dummy_9",
            "AskingRentFrom": 9.14,
            "AskingRentTo": 4.28,
            "MonthlyRentalTo": 1.7,
            "Created_At": "3/9/2020, 03:47:53",
            "Updated_At": "1/14/2021, 08:37:20",
            "floorplan_url": "dummy_5",
            "Floor_id": "dummy_0"
         },
         {
            "InfoUpdateBy": "dummy_0",
            "SpaceUsage": "industrial",
            "Status": "dummy_7",
            "MonthlyRentalFrom": 7.69,
            "Availability": "no",
            "PropertyType": "comercial",
            "SpaceID": "dummy_3",
            "SpaceCondition": "excelent",
            "ID": 4,
            "Property_ID_x": "dummy_6",
            "BuildingName_x": "dummy_4",
            "FloorID": "dummy_4",
            "Floor": "dummy_0",
            "SortOrder": "dummy_6",
            "SpaceName": "dummy_9",
            "Availability_SpaceStatus": "dummy_3",
            "PossessionStatus": "dummy_0",
            "QuotedArea": 6.06,
            "InfoUpdateDate": "8/12/2020, 22:11:36",
            "CreatedBy": "dummy_2",
            "ModifiedBy": "dummy_4",
            "AskingRentFrom": 7.87,
            "AskingRentTo": 3.62,
            "MonthlyRentalTo": 2.11,
            "Created_At": "4/25/2021, 10:56:11",
            "Updated_At": "11/11/2021, 08:27:22",
            "floorplan_url": "dummy_5",
            "Floor_id": "dummy_0"
         },
         {
            "InfoUpdateBy": "dummy_8",
            "SpaceUsage": "industrial",
            "Status": "dummy_6",
            "MonthlyRentalFrom": 4.07,
            "Availability": "yes",
            "PropertyType": "comercial",
            "SpaceID": "dummy_9",
            "SpaceCondition": "need_renovation",
            "ID": 9,
            "Property_ID_x": "dummy_2",
            "BuildingName_x": "dummy_4",
            "FloorID": "dummy_4",
            "Floor": "dummy_3",
            "SortOrder": "dummy_1",
            "SpaceName": "dummy_6",
            "Availability_SpaceStatus": "dummy_6",
            "PossessionStatus": "dummy_2",
            "QuotedArea": 9.77,
            "InfoUpdateDate": "4/9/2018, 14:33:01",
            "CreatedBy": "dummy_5",
            "ModifiedBy": "dummy_0",
            "AskingRentFrom": 7.1,
            "AskingRentTo": 3.68,
            "MonthlyRentalTo": 2.89,
            "Created_At": "6/9/2016, 08:31:33",
            "Updated_At": "3/4/2023, 15:39:34",
            "floorplan_url": "dummy_3",
            "Floor_id": "dummy_3"
         },
         {
            "InfoUpdateBy": "dummy_9",
            "SpaceUsage": "industrial",
            "Status": "dummy_4",
            "MonthlyRentalFrom": 4.73,
            "Availability": "no",
            "PropertyType": "residential",
            "SpaceID": "dummy_2",
            "SpaceCondition": "poor",
            "ID": 8,
            "Property_ID_x": "dummy_9",
            "BuildingName_x": "dummy_3",
            "FloorID": "dummy_7",
            "Floor": "dummy_7",
            "SortOrder": "dummy_6",
            "SpaceName": "dummy_3",
            "Availability_SpaceStatus": "dummy_9",
            "PossessionStatus": "dummy_6",
            "QuotedArea": 5.63,
            "InfoUpdateDate": "8/11/2018, 15:14:35",
            "CreatedBy": "dummy_5",
            "ModifiedBy": "dummy_8",
            "AskingRentFrom": 9.26,
            "AskingRentTo": 9.96,
            "MonthlyRentalTo": 4.22,
            "Created_At": "5/13/2021, 15:18:26",
            "Updated_At": "8/24/2019, 21:51:44",
            "floorplan_url": "dummy_5",
            "Floor_id": "dummy_0"
         }
      ],
      "po_property_3D": [
         {
            "Floor_id": "dummy_1",
            "ID": 6,
            "image_url": "dummy_5",
            "floorplan_url": "dummy_7",
            "asset_class": "Retail",
            "available_units": "no"
         },
         {
            "Floor_id": "dummy_2",
            "ID": 5,
            "image_url": "dummy_0",
            "floorplan_url": "dummy_1",
            "asset_class": "Hospitality",
            "available_units": "no"
         },
         {
            "Floor_id": "dummy_7",
            "ID": 9,
            "image_url": "dummy_4",
            "floorplan_url": "dummy_9",
            "asset_class": "Mixed_use",
            "available_units": "yes"
         },
         {
            "Floor_id": "dummy_4",
            "ID": 9,
            "image_url": "dummy_1",
            "floorplan_url": "dummy_9",
            "asset_class": "Agricultural",
            "available_units": "no"
         },
         {
            "Floor_id": "dummy_5",
            "ID": 9,
            "image_url": "dummy_1",
            "floorplan_url": "dummy_5",
            "asset_class": "Agricultural",
            "available_units": "yes"
         }
      ],
      "shortlist": [
         {
            "share_with": "dummy_8",
            "added_dt": "7/23/2018, 11:11:02",
            "user_id": "dummy_8",
            "Customer_name": "dummy_6",
            "Opportunityname": "dummy_0",
            "name": "dummy_4",
            "ID": 7,
            "available_units": "undefined"
         },
         {
            "share_with": "dummy_8",
            "added_dt": "6/3/2017, 21:21:08",
            "user_id": "dummy_4",
            "Customer_name": "dummy_7",
            "Opportunityname": "dummy_6",
            "name": "dummy_8",
            "ID": 3,
            "available_units": "undefined"
         },
         {
            "share_with": "dummy_5",
            "added_dt": "12/31/2022, 21:13:15",
            "user_id": "dummy_0",
            "Customer_name": "dummy_8",
            "Opportunityname": "dummy_0",
            "name": "dummy_5",
            "ID": 7,
            "available_units": "undefined"
         },
         {
            "share_with": "dummy_8",
            "added_dt": "4/11/2016, 07:23:42",
            "user_id": "dummy_5",
            "Customer_name": "dummy_9",
            "Opportunityname": "dummy_0",
            "name": "dummy_9",
            "ID": 0,
            "available_units": "undefined"
         },
         {
            "share_with": "dummy_3",
            "added_dt": "2/15/2016, 16:48:27",
            "user_id": "dummy_7",
            "Customer_name": "dummy_9",
            "Opportunityname": "dummy_4",
            "name": "dummy_2",
            "ID": 4,
            "available_units": "undefined"
         }
      ],
      "travel_time": [
         {
            "dest_type": "undefined",
            "dest_name": "dummy_5",
            "using": "undefined",
            "km": "dummy_6",
            "min": "dummy_9",
            "action_c": "dummy_5",
            "ID": 9
         },
         {
            "dest_type": "undefined",
            "dest_name": "dummy_7",
            "using": "undefined",
            "km": "dummy_6",
            "min": "dummy_5",
            "action_c": "dummy_6",
            "ID": 7
         },
         {
            "dest_type": "undefined",
            "dest_name": "dummy_5",
            "using": "undefined",
            "km": "dummy_7",
            "min": "dummy_8",
            "action_c": "dummy_7",
            "ID": 8
         },
         {
            "dest_type": "undefined",
            "dest_name": "dummy_4",
            "using": "undefined",
            "km": "dummy_5",
            "min": "dummy_1",
            "action_c": "dummy_5",
            "ID": 7
         },
         {
            "dest_type": "undefined",
            "dest_name": "dummy_0",
            "using": "undefined",
            "km": "dummy_2",
            "min": "dummy_3",
            "action_c": "dummy_0",
            "ID": 9
         }
      ]
   }
},
"outJsonCascade" : {
   "Slug": "dummy_1",
   "Updated_at": "dummy_6",
   "Created_at": "dummy_5",
   "Industry": "dummy_9",
   "ID": 6,
   "Name": "dummy_2",
   "Grade": "good",
   "Country": "Korea",
   "PostalCode": "dummy_6",
   "Street_no": "dummy_1",
   "Street": "dummy_5",
   "Address": "dummy_8",
   "Property_type": "dummy_4",
   "Region": "North",
   "Micromarket": "Central Business District",
   "Zoning": "Industrial",
   "Property_Usage": "Commercial",
   "LandOwnership": "dummy_1",
   "OwnershipStructure_Title": "Freehold",
   "PropertyStatus": "dummy_4",
   "TOPDate": "10/28/2022, 15:58:35",
   "GrossFloorArea": 7.45,
   "LandArea": 7.57,
   "NetLettableArea": 6.42,
   "AreaBreakdown": "dummy_0",
   "Headline": "dummy_1",
   "LocationDescription": "dummy_0",
   "BuildingDescription": "dummy_1",
   "BelowGround": "dummy_1",
   "AboveGround": "dummy_1",
   "TotalFloors": "dummy_9",
   "Tenant": "dummy_0",
   "WithinComplex": "dummy_6",
   "WithinProximity": "dummy_7",
   "Public": "dummy_3",
   "Private": "dummy_3",
   "NoofPassengerLift": "dummy_8",
   "CarParkLifttoG_F": "dummy_9",
   "ServiceLift": "dummy_2",
   "CargoLift": "dummy_3",
   "NoofLiftZone": "dummy_9",
   "CarParkLots": "dummy_5",
   "AllocationRatio": "dummy_4",
   "UOM_AllocationRatio": "dummy_3",
   "ParkingDetails": "dummy_1",
   "Seasonal": "dummy_4",
   "Non_Reserved": "dummy_4",
   "MRT1": "dummy_0",
   "MRT1CoveredAccess": "dummy_1",
   "MRT1Walk_Drive": "dummy_7",
   "MRT1Time_Mins": "dummy_0",
   "MRT2": "dummy_6",
   "MRT2CoveredAccess": "dummy_9",
   "MRT2Walk_Drive": "dummy_4",
   "MRT2Time_Mins_": "dummy_8",
   "MRT3": "dummy_4",
   "MRT3CoveredAccess": "dummy_5",
   "MRT3Walk_Drive": "dummy_3",
   "MRT3Time_Mins": "dummy_2",
   "Bus": "dummy_4",
   "Others": "dummy_5",
   "FloorToCeilingHeight_From": 4.65,
   "FloorToCeilingHeight_To": 4.75,
   "FloorLoadingRange_From": 6.83,
   "FloorLoadingRange_To": 7.21,
   "CeilingGrid_FloorLoadingDetails": "dummy_7",
   "FloorSystem": "dummy_0",
   "PowerSystem": "dummy_3",
   "NoOfOfficeFloors": 3.17,
   "TypicalMinimumFloorSize": "dummy_1",
   "MaximumFloorSize_SqFt": "dummy_0",
   "UltraHigh_TopFloor": "dummy_6",
   "High_TopFloor": "yes",
   "Mid_TopFloor": "yes",
   "Low_TopFloor": "no",
   "TypeOfUse": "dummy_4",
   "NoOfLoadingBays": "dummy_9",
   "AccessibleFor": "dummy_8",
   "Loading_UnloadingBay": "dummy_4",
   "NoOfCranes": "dummy_2",
   "OtherDetails": "dummy_7",
   "NoOfRetailFloors": "dummy_3",
   "Kind": "dummy_9",
   "AccountName": "dummy_7",
   "lists": {
      "space_info": [
         {
            "InfoUpdateBy": "dummy_6",
            "SpaceUsage": "comercial",
            "Status": "dummy_9",
            "MonthlyRentalFrom": 6.49,
            "Availability": "no",
            "PropertyType": "Office",
            "SpaceID": "dummy_9",
            "SpaceCondition": "excelent",
            "ID": 5,
            "Property_ID_x": "dummy_8",
            "BuildingName_x": "dummy_5",
            "FloorID": "dummy_4",
            "Floor": "dummy_9",
            "SortOrder": "dummy_3",
            "SpaceName": "dummy_9",
            "Availability_SpaceStatus": "dummy_9",
            "PossessionStatus": "dummy_8",
            "QuotedArea": 2.42,
            "InfoUpdateDate": "4/21/2021, 06:53:15",
            "CreatedBy": "dummy_3",
            "ModifiedBy": "dummy_1",
            "AskingRentFrom": 8.53,
            "AskingRentTo": 8.7,
            "MonthlyRentalTo": 5.72,
            "Created_At": "4/2/2019, 10:13:05",
            "Updated_At": "11/21/2022, 05:31:41",
            "space_info": {
               "floorplan_url": "dummy_9",
               "Floor_id": "dummy_0"
            }
         },
         {
            "InfoUpdateBy": "dummy_1",
            "SpaceUsage": "industrial",
            "Status": "dummy_2",
            "MonthlyRentalFrom": 6.76,
            "Availability": "yes",
            "PropertyType": "comercial",
            "SpaceID": "dummy_6",
            "SpaceCondition": "poor",
            "ID": 2,
            "Property_ID_x": "dummy_5",
            "BuildingName_x": "dummy_9",
            "FloorID": "dummy_3",
            "Floor": "dummy_7",
            "SortOrder": "dummy_6",
            "SpaceName": "dummy_3",
            "Availability_SpaceStatus": "dummy_2",
            "PossessionStatus": "dummy_1",
            "QuotedArea": 2.74,
            "InfoUpdateDate": "5/5/2022, 14:34:27",
            "CreatedBy": "dummy_8",
            "ModifiedBy": "dummy_5",
            "AskingRentFrom": 8.35,
            "AskingRentTo": 9.63,
            "MonthlyRentalTo": 2.2,
            "Created_At": "9/22/2017, 03:17:59",
            "Updated_At": "8/20/2022, 24:59:05",
            "space_info": {
               "floorplan_url": "dummy_5",
               "Floor_id": "dummy_0"
            }
         },
         {
            "InfoUpdateBy": "dummy_7",
            "SpaceUsage": "industrial",
            "Status": "dummy_8",
            "MonthlyRentalFrom": 2.44,
            "Availability": "no",
            "PropertyType": "Office",
            "SpaceID": "dummy_5",
            "SpaceCondition": "average",
            "ID": 7,
            "Property_ID_x": "dummy_3",
            "BuildingName_x": "dummy_1",
            "FloorID": "dummy_6",
            "Floor": "dummy_3",
            "SortOrder": "dummy_1",
            "SpaceName": "dummy_4",
            "Availability_SpaceStatus": "dummy_9",
            "PossessionStatus": "dummy_8",
            "QuotedArea": 1.04,
            "InfoUpdateDate": "10/21/2020, 03:52:55",
            "CreatedBy": "dummy_4",
            "ModifiedBy": "dummy_3",
            "AskingRentFrom": 4.47,
            "AskingRentTo": 3.67,
            "MonthlyRentalTo": 9.65,
            "Created_At": "8/12/2022, 16:26:27",
            "Updated_At": "8/14/2015, 05:25:59",
            "space_info": {
               "floorplan_url": "dummy_5",
               "Floor_id": "dummy_2"
            }
         },
         {
            "InfoUpdateBy": "dummy_8",
            "SpaceUsage": "industrial",
            "Status": "dummy_7",
            "MonthlyRentalFrom": 4.27,
            "Availability": "yes",
            "PropertyType": "Office",
            "SpaceID": "dummy_4",
            "SpaceCondition": "excelent",
            "ID": 8,
            "Property_ID_x": "dummy_7",
            "BuildingName_x": "dummy_9",
            "FloorID": "dummy_9",
            "Floor": "dummy_8",
            "SortOrder": "dummy_4",
            "SpaceName": "dummy_1",
            "Availability_SpaceStatus": "dummy_7",
            "PossessionStatus": "dummy_8",
            "QuotedArea": 6.02,
            "InfoUpdateDate": "11/9/2016, 18:51:06",
            "CreatedBy": "dummy_3",
            "ModifiedBy": "dummy_8",
            "AskingRentFrom": 2.24,
            "AskingRentTo": 3.62,
            "MonthlyRentalTo": 7.63,
            "Created_At": "5/13/2017, 20:42:08",
            "Updated_At": "11/27/2015, 23:45:33",
            "space_info": {
               "floorplan_url": "dummy_6",
               "Floor_id": "dummy_3"
            }
         },
         {
            "InfoUpdateBy": "dummy_8",
            "SpaceUsage": "industrial",
            "Status": "dummy_9",
            "MonthlyRentalFrom": 1.25,
            "Availability": "no",
            "PropertyType": "residential",
            "SpaceID": "dummy_9",
            "SpaceCondition": "excelent",
            "ID": 7,
            "Property_ID_x": "dummy_9",
            "BuildingName_x": "dummy_8",
            "FloorID": "dummy_3",
            "Floor": "dummy_6",
            "SortOrder": "dummy_8",
            "SpaceName": "dummy_5",
            "Availability_SpaceStatus": "dummy_6",
            "PossessionStatus": "dummy_3",
            "QuotedArea": 3.41,
            "InfoUpdateDate": "9/6/2015, 04:44:32",
            "CreatedBy": "dummy_3",
            "ModifiedBy": "dummy_3",
            "AskingRentFrom": 7.63,
            "AskingRentTo": 1.3,
            "MonthlyRentalTo": 9.74,
            "Created_At": "3/13/2020, 07:30:50",
            "Updated_At": "10/23/2022, 19:18:36",
            "space_info": {
               "floorplan_url": "dummy_9",
               "Floor_id": "dummy_5"
            }
         }
      ],
      "po_property_3D": [
         {
            "Floor_id": "dummy_6",
            "ID": 3,
            "image_url": "dummy_6",
            "floorplan_url": "dummy_5",
            "asset_class": "Agricultural",
            "available_units": "no"
         },
         {
            "Floor_id": "dummy_8",
            "ID": 5,
            "image_url": "dummy_1",
            "floorplan_url": "dummy_0",
            "asset_class": "Commercial",
            "available_units": "yes"
         },
         {
            "Floor_id": "dummy_3",
            "ID": 9,
            "image_url": "dummy_1",
            "floorplan_url": "dummy_2",
            "asset_class": "Retail",
            "available_units": "no"
         },
         {
            "Floor_id": "dummy_0",
            "ID": 9,
            "image_url": "dummy_1",
            "floorplan_url": "dummy_8",
            "asset_class": "Industrial",
            "available_units": "no"
         },
         {
            "Floor_id": "dummy_9",
            "ID": 4,
            "image_url": "dummy_6",
            "floorplan_url": "dummy_5",
            "asset_class": "Industrial",
            "available_units": "no"
         }
      ],
      "shortlist": [
         {
            "share_with": "dummy_4",
            "added_dt": "10/14/2019, 11:00:33",
            "user_id": "dummy_5",
            "Customer_name": "dummy_1",
            "Opportunityname": "dummy_5",
            "name": "dummy_4",
            "ID": 3,
            "available_units": "undefined"
         },
         {
            "share_with": "dummy_0",
            "added_dt": "5/30/2017, 20:25:35",
            "user_id": "dummy_8",
            "Customer_name": "dummy_5",
            "Opportunityname": "dummy_0",
            "name": "dummy_0",
            "ID": 8,
            "available_units": "undefined"
         },
         {
            "share_with": "dummy_7",
            "added_dt": "12/5/2022, 10:56:24",
            "user_id": "dummy_3",
            "Customer_name": "dummy_6",
            "Opportunityname": "dummy_2",
            "name": "dummy_6",
            "ID": 6,
            "available_units": "undefined"
         },
         {
            "share_with": "dummy_0",
            "added_dt": "2/23/2021, 18:02:47",
            "user_id": "dummy_0",
            "Customer_name": "dummy_8",
            "Opportunityname": "dummy_2",
            "name": "dummy_5",
            "ID": 4,
            "available_units": "undefined"
         },
         {
            "share_with": "dummy_9",
            "added_dt": "11/20/2016, 16:53:49",
            "user_id": "dummy_6",
            "Customer_name": "dummy_0",
            "Opportunityname": "dummy_6",
            "name": "dummy_5",
            "ID": 7,
            "available_units": "undefined"
         }
      ],
      "travel_time": [
         {
            "dest_type": "undefined",
            "dest_name": "dummy_4",
            "using": "undefined",
            "km": "dummy_5",
            "min": "dummy_8",
            "action_c": "dummy_4",
            "ID": 7
         },
         {
            "dest_type": "undefined",
            "dest_name": "dummy_9",
            "using": "undefined",
            "km": "dummy_3",
            "min": "dummy_7",
            "action_c": "dummy_7",
            "ID": 2
         },
         {
            "dest_type": "undefined",
            "dest_name": "dummy_8",
            "using": "undefined",
            "km": "dummy_1",
            "min": "dummy_2",
            "action_c": "dummy_1",
            "ID": 9
         },
         {
            "dest_type": "undefined",
            "dest_name": "dummy_5",
            "using": "undefined",
            "km": "dummy_2",
            "min": "dummy_0",
            "action_c": "dummy_4",
            "ID": 4
         },
         {
            "dest_type": "undefined",
            "dest_name": "dummy_6",
            "using": "undefined",
            "km": "dummy_5",
            "min": "dummy_2",
            "action_c": "dummy_3",
            "ID": 3
         }
      ]
   }
}
}