{ "formStruct" : {
   "fields": {
      "city>name": {
         "name": "city>name",
         "label": "name",
         "type": "VARCHAR(100)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      },
      "city>Contry": {
         "name": "city>Contry",
         "label": "Contry",
         "type": "VARCHAR(50)",
         "inherit": "",
         "inForm": "true",
         "query": "false",
         "results": "false",
         "viewField": "true",
         "editField": "true",
         "compulField": "true",
         "validateField": "true"
      }
   },
   "lists": {
      "po_property_3D": {
         "label": "po property 3D",
         "fields": [
            {
               "name": "po_property_3D>asset_class",
               "label": "po property 3D asset class",
               "type": "ENUM(50)",
               "inherit": ""
            },
            {
               "name": "po_property_3D>available_units",
               "label": "po property 3D available units",
               "type": "ENUM(50)",
               "inherit": ""
            },
            {
               "name": "po_property_3D>floorplan_url",
               "label": "po property 3D floorplan url",
               "type": "VARCHAR(100)",
               "inherit": ""
            },
            {
               "name": "po_property_3D>image_url",
               "label": "po property 3D image url",
               "type": "VARCHAR(200)",
               "inherit": ""
            },
            {
               "name": "po_property_3D>ID",
               "label": "po property 3D ID",
               "type": "INTEGER",
               "inherit": ""
            },
            {
               "name": "prop_info>ID",
               "label": "prop info ID",
               "type": "INTEGER",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Name",
               "label": "prop info Name",
               "type": "VARCHAR(200)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Grade",
               "label": "prop info Grade",
               "type": "ENUM(50)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Country",
               "label": "prop info Country",
               "type": "ENUM(50)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>PostalCode",
               "label": "prop info PostalCode",
               "type": "int",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Street_no",
               "label": "prop info Street no",
               "type": "VARCHAR(10)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Street",
               "label": "prop info Street",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Address",
               "label": "prop info Address",
               "type": "VARCHAR(200)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Property_type",
               "label": "prop info Property type",
               "type": "VARCHAR(300)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Region",
               "label": "prop info Region",
               "type": "ENUM(50)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Micromarket",
               "label": "prop info Micromarket",
               "type": "ENUM(50)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Zoning",
               "label": "prop info Zoning",
               "type": "ENUM(50)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Property_Usage",
               "label": "prop info Property Usage",
               "type": "ENUM(50)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>LandOwnership",
               "label": "prop info LandOwnership",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>OwnershipStructure_Title",
               "label": "prop info OwnershipStructure Title",
               "type": "ENUM(50)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>PropertyStatus",
               "label": "prop info PropertyStatus",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>TOPDate",
               "label": "prop info TOPDate",
               "type": "datetime",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>GrossFloorArea",
               "label": "prop info GrossFloorArea",
               "type": "decimal(12,2)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>LandArea",
               "label": "prop info LandArea",
               "type": "decimal(12,2)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>NetLettableArea",
               "label": "prop info NetLettableArea",
               "type": "decimal(12,2)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>AreaBreakdown",
               "label": "prop info AreaBreakdown",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Headline",
               "label": "prop info Headline",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>LocationDescription",
               "label": "prop info LocationDescription",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>BuildingDescription",
               "label": "prop info BuildingDescription",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>BelowGround",
               "label": "prop info BelowGround",
               "type": "int",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>AboveGround",
               "label": "prop info AboveGround",
               "type": "int",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>TotalFloors",
               "label": "prop info TotalFloors",
               "type": "int",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Tenant",
               "label": "prop info Tenant",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>WithinComplex",
               "label": "prop info WithinComplex",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>WithinProximity",
               "label": "prop info WithinProximity",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Public",
               "label": "prop info Public",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Private",
               "label": "prop info Private",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>NoofPassengerLift",
               "label": "prop info NoofPassengerLift",
               "type": "int",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>CarParkLifttoG_F",
               "label": "prop info CarParkLifttoG F",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>ServiceLift",
               "label": "prop info ServiceLift",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>CargoLift",
               "label": "prop info CargoLift",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>NoofLiftZone",
               "label": "prop info NoofLiftZone",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>CarParkLots",
               "label": "prop info CarParkLots",
               "type": "int",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>AllocationRatio",
               "label": "prop info AllocationRatio",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>UOM_AllocationRatio",
               "label": "prop info UOM AllocationRatio",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>ParkingDetails",
               "label": "prop info ParkingDetails",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Seasonal",
               "label": "prop info Seasonal",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Non_Reserved",
               "label": "prop info Non Reserved",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>MRT1",
               "label": "prop info MRT1",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>MRT1CoveredAccess",
               "label": "prop info MRT1CoveredAccess",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>MRT1Walk_Drive",
               "label": "prop info MRT1Walk Drive",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>MRT1Time_Mins",
               "label": "prop info MRT1Time Mins",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>MRT2",
               "label": "prop info MRT2",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>MRT2CoveredAccess",
               "label": "prop info MRT2CoveredAccess",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>MRT2Walk_Drive",
               "label": "prop info MRT2Walk Drive",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>MRT2Time_Mins_",
               "label": "prop info MRT2Time Mins ",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>MRT3",
               "label": "prop info MRT3",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>MRT3CoveredAccess",
               "label": "prop info MRT3CoveredAccess",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>MRT3Walk_Drive",
               "label": "prop info MRT3Walk Drive",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>MRT3Time_Mins",
               "label": "prop info MRT3Time Mins",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Bus",
               "label": "prop info Bus",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Others",
               "label": "prop info Others",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>FloorToCeilingHeight_From",
               "label": "prop info FloorToCeilingHeight From",
               "type": "decimal(12,2)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>FloorToCeilingHeight_To",
               "label": "prop info FloorToCeilingHeight To",
               "type": "decimal(12,2)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>FloorLoadingRange_From",
               "label": "prop info FloorLoadingRange From",
               "type": "decimal(12,2)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>FloorLoadingRange_To",
               "label": "prop info FloorLoadingRange To",
               "type": "decimal(12,2)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>CeilingGrid_FloorLoadingDetails",
               "label": "prop info CeilingGrid FloorLoadingDetails",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>FloorSystem",
               "label": "prop info FloorSystem",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>PowerSystem",
               "label": "prop info PowerSystem",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>NoOfOfficeFloors",
               "label": "prop info NoOfOfficeFloors",
               "type": "decimal(12,2)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>TypicalMinimumFloorSize",
               "label": "prop info TypicalMinimumFloorSize",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>MaximumFloorSize_SqFt",
               "label": "prop info MaximumFloorSize SqFt",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>UltraHigh_TopFloor",
               "label": "prop info UltraHigh TopFloor",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>High_TopFloor",
               "label": "prop info High TopFloor",
               "type": "ENUM(50)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Mid_TopFloor",
               "label": "prop info Mid TopFloor",
               "type": "ENUM(50)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Low_TopFloor",
               "label": "prop info Low TopFloor",
               "type": "ENUM(50)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>TypeOfUse",
               "label": "prop info TypeOfUse",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>NoOfLoadingBays",
               "label": "prop info NoOfLoadingBays",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>AccessibleFor",
               "label": "prop info AccessibleFor",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Loading_UnloadingBay",
               "label": "prop info Loading UnloadingBay",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>NoOfCranes",
               "label": "prop info NoOfCranes",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>OtherDetails",
               "label": "prop info OtherDetails",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>NoOfRetailFloors",
               "label": "prop info NoOfRetailFloors",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Kind",
               "label": "prop info Kind",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>AccountName",
               "label": "prop info AccountName",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Slug",
               "label": "prop info Slug",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Updated_at",
               "label": "prop info Updated at",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Created_at",
               "label": "prop info Created at",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            },
            {
               "name": "prop_info>Industry",
               "label": "prop info Industry",
               "type": "VARCHAR(100)",
               "inherit": "> (prop_info,po_property_3D,prop_info_po_property_3D) "
            }
         ]
      }
   },
   "entity": "city"
},
 "sampleDataList" : {
   "name": "name_9",
   "Contry": "Contry_5",
   "lists": {
      "po_property_3D": [
         {
            "asset_class": "Special purpose",
            "available_units": "no",
            "floorplan_url": "floorplan_url_6",
            "image_url": "image_url_0",
            "ID": 0,
            "Name": "Name_3",
            "Grade": "undefined",
            "Country": "undefined",
            "PostalCode": "PostalCode_1",
            "Street_no": "Street_no_4",
            "Street": "Street_4",
            "Address": "Address_6",
            "Property_type": "Property_type_7",
            "Region": "undefined",
            "Micromarket": "undefined",
            "Zoning": "undefined",
            "Property_Usage": "undefined",
            "LandOwnership": "LandOwnership_6",
            "OwnershipStructure_Title": "undefined",
            "PropertyStatus": "PropertyStatus_1",
            "TOPDate": "5/11/2018, 07:42:12",
            "GrossFloorArea": 2.26,
            "LandArea": 1.03,
            "NetLettableArea": 4.07,
            "AreaBreakdown": "AreaBreakdown_0",
            "Headline": "Headline_3",
            "LocationDescription": "LocationDescription_7",
            "BuildingDescription": "BuildingDescription_3",
            "BelowGround": "BelowGround_2",
            "AboveGround": "AboveGround_9",
            "TotalFloors": "TotalFloors_4",
            "Tenant": "Tenant_8",
            "WithinComplex": "WithinComplex_0",
            "WithinProximity": "WithinProximity_0",
            "Public": "Public_8",
            "Private": "Private_2",
            "NoofPassengerLift": "NoofPassengerLift_8",
            "CarParkLifttoG_F": "CarParkLifttoG_F_7",
            "ServiceLift": "ServiceLift_7",
            "CargoLift": "CargoLift_1",
            "NoofLiftZone": "NoofLiftZone_1",
            "CarParkLots": "CarParkLots_2",
            "AllocationRatio": "AllocationRatio_8",
            "UOM_AllocationRatio": "UOM_AllocationRatio_2",
            "ParkingDetails": "ParkingDetails_8",
            "Seasonal": "Seasonal_4",
            "Non_Reserved": "Non_Reserved_1",
            "MRT1": "MRT1_6",
            "MRT1CoveredAccess": "MRT1CoveredAccess_8",
            "MRT1Walk_Drive": "MRT1Walk_Drive_1",
            "MRT1Time_Mins": "MRT1Time_Mins_7",
            "MRT2": "MRT2_2",
            "MRT2CoveredAccess": "MRT2CoveredAccess_4",
            "MRT2Walk_Drive": "MRT2Walk_Drive_9",
            "MRT2Time_Mins_": "MRT2Time_Mins__2",
            "MRT3": "MRT3_2",
            "MRT3CoveredAccess": "MRT3CoveredAccess_6",
            "MRT3Walk_Drive": "MRT3Walk_Drive_6",
            "MRT3Time_Mins": "MRT3Time_Mins_2",
            "Bus": "Bus_1",
            "Others": "Others_5",
            "FloorToCeilingHeight_From": 8.73,
            "FloorToCeilingHeight_To": 2.33,
            "FloorLoadingRange_From": 2.02,
            "FloorLoadingRange_To": 6.29,
            "CeilingGrid_FloorLoadingDetails": "CeilingGrid_FloorLoadingDetails_4",
            "FloorSystem": "FloorSystem_0",
            "PowerSystem": "PowerSystem_9",
            "NoOfOfficeFloors": 3.16,
            "TypicalMinimumFloorSize": "TypicalMinimumFloorSize_0",
            "MaximumFloorSize_SqFt": "MaximumFloorSize_SqFt_9",
            "UltraHigh_TopFloor": "UltraHigh_TopFloor_7",
            "High_TopFloor": "undefined",
            "Mid_TopFloor": "undefined",
            "Low_TopFloor": "undefined",
            "TypeOfUse": "TypeOfUse_9",
            "NoOfLoadingBays": "NoOfLoadingBays_0",
            "AccessibleFor": "AccessibleFor_0",
            "Loading_UnloadingBay": "Loading_UnloadingBay_9",
            "NoOfCranes": "NoOfCranes_4",
            "OtherDetails": "OtherDetails_8",
            "NoOfRetailFloors": "NoOfRetailFloors_9",
            "Kind": "Kind_7",
            "AccountName": "AccountName_5",
            "Slug": "Slug_9",
            "Updated_at": "Updated_at_9",
            "Created_at": "Created_at_1",
            "Industry": "Industry_2"
         },
         {
            "asset_class": "Hospitality",
            "available_units": "no",
            "floorplan_url": "floorplan_url_3",
            "image_url": "image_url_1",
            "ID": 2,
            "Name": "Name_1",
            "Grade": "undefined",
            "Country": "undefined",
            "PostalCode": "PostalCode_7",
            "Street_no": "Street_no_7",
            "Street": "Street_3",
            "Address": "Address_1",
            "Property_type": "Property_type_0",
            "Region": "undefined",
            "Micromarket": "undefined",
            "Zoning": "undefined",
            "Property_Usage": "undefined",
            "LandOwnership": "LandOwnership_2",
            "OwnershipStructure_Title": "undefined",
            "PropertyStatus": "PropertyStatus_0",
            "TOPDate": "11/21/2022, 02:18:20",
            "GrossFloorArea": 7.33,
            "LandArea": 6.26,
            "NetLettableArea": 9.9,
            "AreaBreakdown": "AreaBreakdown_4",
            "Headline": "Headline_8",
            "LocationDescription": "LocationDescription_1",
            "BuildingDescription": "BuildingDescription_1",
            "BelowGround": "BelowGround_1",
            "AboveGround": "AboveGround_7",
            "TotalFloors": "TotalFloors_3",
            "Tenant": "Tenant_7",
            "WithinComplex": "WithinComplex_9",
            "WithinProximity": "WithinProximity_7",
            "Public": "Public_0",
            "Private": "Private_8",
            "NoofPassengerLift": "NoofPassengerLift_2",
            "CarParkLifttoG_F": "CarParkLifttoG_F_0",
            "ServiceLift": "ServiceLift_1",
            "CargoLift": "CargoLift_8",
            "NoofLiftZone": "NoofLiftZone_8",
            "CarParkLots": "CarParkLots_3",
            "AllocationRatio": "AllocationRatio_6",
            "UOM_AllocationRatio": "UOM_AllocationRatio_5",
            "ParkingDetails": "ParkingDetails_3",
            "Seasonal": "Seasonal_5",
            "Non_Reserved": "Non_Reserved_9",
            "MRT1": "MRT1_4",
            "MRT1CoveredAccess": "MRT1CoveredAccess_7",
            "MRT1Walk_Drive": "MRT1Walk_Drive_0",
            "MRT1Time_Mins": "MRT1Time_Mins_6",
            "MRT2": "MRT2_2",
            "MRT2CoveredAccess": "MRT2CoveredAccess_1",
            "MRT2Walk_Drive": "MRT2Walk_Drive_3",
            "MRT2Time_Mins_": "MRT2Time_Mins__2",
            "MRT3": "MRT3_7",
            "MRT3CoveredAccess": "MRT3CoveredAccess_4",
            "MRT3Walk_Drive": "MRT3Walk_Drive_2",
            "MRT3Time_Mins": "MRT3Time_Mins_7",
            "Bus": "Bus_5",
            "Others": "Others_7",
            "FloorToCeilingHeight_From": 6.6,
            "FloorToCeilingHeight_To": 9.97,
            "FloorLoadingRange_From": 8.66,
            "FloorLoadingRange_To": 6.38,
            "CeilingGrid_FloorLoadingDetails": "CeilingGrid_FloorLoadingDetails_2",
            "FloorSystem": "FloorSystem_3",
            "PowerSystem": "PowerSystem_5",
            "NoOfOfficeFloors": 9.77,
            "TypicalMinimumFloorSize": "TypicalMinimumFloorSize_8",
            "MaximumFloorSize_SqFt": "MaximumFloorSize_SqFt_7",
            "UltraHigh_TopFloor": "UltraHigh_TopFloor_7",
            "High_TopFloor": "undefined",
            "Mid_TopFloor": "undefined",
            "Low_TopFloor": "undefined",
            "TypeOfUse": "TypeOfUse_6",
            "NoOfLoadingBays": "NoOfLoadingBays_4",
            "AccessibleFor": "AccessibleFor_0",
            "Loading_UnloadingBay": "Loading_UnloadingBay_3",
            "NoOfCranes": "NoOfCranes_1",
            "OtherDetails": "OtherDetails_6",
            "NoOfRetailFloors": "NoOfRetailFloors_2",
            "Kind": "Kind_4",
            "AccountName": "AccountName_0",
            "Slug": "Slug_0",
            "Updated_at": "Updated_at_6",
            "Created_at": "Created_at_2",
            "Industry": "Industry_9"
         },
         {
            "asset_class": "Special purpose",
            "available_units": "yes",
            "floorplan_url": "floorplan_url_2",
            "image_url": "image_url_1",
            "ID": 1,
            "Name": "Name_5",
            "Grade": "undefined",
            "Country": "undefined",
            "PostalCode": "PostalCode_5",
            "Street_no": "Street_no_7",
            "Street": "Street_1",
            "Address": "Address_9",
            "Property_type": "Property_type_4",
            "Region": "undefined",
            "Micromarket": "undefined",
            "Zoning": "undefined",
            "Property_Usage": "undefined",
            "LandOwnership": "LandOwnership_1",
            "OwnershipStructure_Title": "undefined",
            "PropertyStatus": "PropertyStatus_8",
            "TOPDate": "2/27/2016, 02:11:14",
            "GrossFloorArea": 5.71,
            "LandArea": 3.32,
            "NetLettableArea": 6.07,
            "AreaBreakdown": "AreaBreakdown_1",
            "Headline": "Headline_9",
            "LocationDescription": "LocationDescription_7",
            "BuildingDescription": "BuildingDescription_5",
            "BelowGround": "BelowGround_6",
            "AboveGround": "AboveGround_1",
            "TotalFloors": "TotalFloors_3",
            "Tenant": "Tenant_5",
            "WithinComplex": "WithinComplex_3",
            "WithinProximity": "WithinProximity_0",
            "Public": "Public_7",
            "Private": "Private_0",
            "NoofPassengerLift": "NoofPassengerLift_4",
            "CarParkLifttoG_F": "CarParkLifttoG_F_7",
            "ServiceLift": "ServiceLift_2",
            "CargoLift": "CargoLift_4",
            "NoofLiftZone": "NoofLiftZone_4",
            "CarParkLots": "CarParkLots_3",
            "AllocationRatio": "AllocationRatio_0",
            "UOM_AllocationRatio": "UOM_AllocationRatio_5",
            "ParkingDetails": "ParkingDetails_9",
            "Seasonal": "Seasonal_8",
            "Non_Reserved": "Non_Reserved_3",
            "MRT1": "MRT1_5",
            "MRT1CoveredAccess": "MRT1CoveredAccess_5",
            "MRT1Walk_Drive": "MRT1Walk_Drive_2",
            "MRT1Time_Mins": "MRT1Time_Mins_3",
            "MRT2": "MRT2_8",
            "MRT2CoveredAccess": "MRT2CoveredAccess_0",
            "MRT2Walk_Drive": "MRT2Walk_Drive_1",
            "MRT2Time_Mins_": "MRT2Time_Mins__5",
            "MRT3": "MRT3_0",
            "MRT3CoveredAccess": "MRT3CoveredAccess_1",
            "MRT3Walk_Drive": "MRT3Walk_Drive_4",
            "MRT3Time_Mins": "MRT3Time_Mins_5",
            "Bus": "Bus_0",
            "Others": "Others_9",
            "FloorToCeilingHeight_From": 2.74,
            "FloorToCeilingHeight_To": 4.05,
            "FloorLoadingRange_From": 3.05,
            "FloorLoadingRange_To": 7.97,
            "CeilingGrid_FloorLoadingDetails": "CeilingGrid_FloorLoadingDetails_4",
            "FloorSystem": "FloorSystem_4",
            "PowerSystem": "PowerSystem_4",
            "NoOfOfficeFloors": 9.2,
            "TypicalMinimumFloorSize": "TypicalMinimumFloorSize_0",
            "MaximumFloorSize_SqFt": "MaximumFloorSize_SqFt_1",
            "UltraHigh_TopFloor": "UltraHigh_TopFloor_8",
            "High_TopFloor": "undefined",
            "Mid_TopFloor": "undefined",
            "Low_TopFloor": "undefined",
            "TypeOfUse": "TypeOfUse_8",
            "NoOfLoadingBays": "NoOfLoadingBays_6",
            "AccessibleFor": "AccessibleFor_3",
            "Loading_UnloadingBay": "Loading_UnloadingBay_1",
            "NoOfCranes": "NoOfCranes_6",
            "OtherDetails": "OtherDetails_3",
            "NoOfRetailFloors": "NoOfRetailFloors_5",
            "Kind": "Kind_8",
            "AccountName": "AccountName_0",
            "Slug": "Slug_3",
            "Updated_at": "Updated_at_6",
            "Created_at": "Created_at_8",
            "Industry": "Industry_1"
         },
         {
            "asset_class": "Mixed_use",
            "available_units": "yes",
            "floorplan_url": "floorplan_url_0",
            "image_url": "image_url_0",
            "ID": 2,
            "Name": "Name_5",
            "Grade": "undefined",
            "Country": "undefined",
            "PostalCode": "PostalCode_2",
            "Street_no": "Street_no_6",
            "Street": "Street_2",
            "Address": "Address_5",
            "Property_type": "Property_type_3",
            "Region": "undefined",
            "Micromarket": "undefined",
            "Zoning": "undefined",
            "Property_Usage": "undefined",
            "LandOwnership": "LandOwnership_7",
            "OwnershipStructure_Title": "undefined",
            "PropertyStatus": "PropertyStatus_4",
            "TOPDate": "9/10/2016, 22:23:14",
            "GrossFloorArea": 1.76,
            "LandArea": 3.57,
            "NetLettableArea": 5.89,
            "AreaBreakdown": "AreaBreakdown_1",
            "Headline": "Headline_7",
            "LocationDescription": "LocationDescription_6",
            "BuildingDescription": "BuildingDescription_2",
            "BelowGround": "BelowGround_3",
            "AboveGround": "AboveGround_4",
            "TotalFloors": "TotalFloors_6",
            "Tenant": "Tenant_8",
            "WithinComplex": "WithinComplex_8",
            "WithinProximity": "WithinProximity_1",
            "Public": "Public_5",
            "Private": "Private_2",
            "NoofPassengerLift": "NoofPassengerLift_5",
            "CarParkLifttoG_F": "CarParkLifttoG_F_6",
            "ServiceLift": "ServiceLift_8",
            "CargoLift": "CargoLift_0",
            "NoofLiftZone": "NoofLiftZone_2",
            "CarParkLots": "CarParkLots_2",
            "AllocationRatio": "AllocationRatio_4",
            "UOM_AllocationRatio": "UOM_AllocationRatio_4",
            "ParkingDetails": "ParkingDetails_1",
            "Seasonal": "Seasonal_0",
            "Non_Reserved": "Non_Reserved_6",
            "MRT1": "MRT1_7",
            "MRT1CoveredAccess": "MRT1CoveredAccess_7",
            "MRT1Walk_Drive": "MRT1Walk_Drive_5",
            "MRT1Time_Mins": "MRT1Time_Mins_7",
            "MRT2": "MRT2_0",
            "MRT2CoveredAccess": "MRT2CoveredAccess_2",
            "MRT2Walk_Drive": "MRT2Walk_Drive_1",
            "MRT2Time_Mins_": "MRT2Time_Mins__5",
            "MRT3": "MRT3_1",
            "MRT3CoveredAccess": "MRT3CoveredAccess_5",
            "MRT3Walk_Drive": "MRT3Walk_Drive_3",
            "MRT3Time_Mins": "MRT3Time_Mins_8",
            "Bus": "Bus_7",
            "Others": "Others_6",
            "FloorToCeilingHeight_From": 4.33,
            "FloorToCeilingHeight_To": 6.74,
            "FloorLoadingRange_From": 5.91,
            "FloorLoadingRange_To": 8.04,
            "CeilingGrid_FloorLoadingDetails": "CeilingGrid_FloorLoadingDetails_9",
            "FloorSystem": "FloorSystem_1",
            "PowerSystem": "PowerSystem_0",
            "NoOfOfficeFloors": 4.99,
            "TypicalMinimumFloorSize": "TypicalMinimumFloorSize_2",
            "MaximumFloorSize_SqFt": "MaximumFloorSize_SqFt_9",
            "UltraHigh_TopFloor": "UltraHigh_TopFloor_8",
            "High_TopFloor": "undefined",
            "Mid_TopFloor": "undefined",
            "Low_TopFloor": "undefined",
            "TypeOfUse": "TypeOfUse_9",
            "NoOfLoadingBays": "NoOfLoadingBays_5",
            "AccessibleFor": "AccessibleFor_0",
            "Loading_UnloadingBay": "Loading_UnloadingBay_6",
            "NoOfCranes": "NoOfCranes_2",
            "OtherDetails": "OtherDetails_5",
            "NoOfRetailFloors": "NoOfRetailFloors_7",
            "Kind": "Kind_5",
            "AccountName": "AccountName_2",
            "Slug": "Slug_8",
            "Updated_at": "Updated_at_6",
            "Created_at": "Created_at_5",
            "Industry": "Industry_3"
         },
         {
            "asset_class": "Commercial",
            "available_units": "no",
            "floorplan_url": "floorplan_url_2",
            "image_url": "image_url_6",
            "ID": 6,
            "Name": "Name_8",
            "Grade": "undefined",
            "Country": "undefined",
            "PostalCode": "PostalCode_5",
            "Street_no": "Street_no_9",
            "Street": "Street_0",
            "Address": "Address_7",
            "Property_type": "Property_type_4",
            "Region": "undefined",
            "Micromarket": "undefined",
            "Zoning": "undefined",
            "Property_Usage": "undefined",
            "LandOwnership": "LandOwnership_0",
            "OwnershipStructure_Title": "undefined",
            "PropertyStatus": "PropertyStatus_8",
            "TOPDate": "5/5/2019, 06:44:20",
            "GrossFloorArea": 9.08,
            "LandArea": 3.62,
            "NetLettableArea": 9.67,
            "AreaBreakdown": "AreaBreakdown_5",
            "Headline": "Headline_6",
            "LocationDescription": "LocationDescription_5",
            "BuildingDescription": "BuildingDescription_0",
            "BelowGround": "BelowGround_0",
            "AboveGround": "AboveGround_2",
            "TotalFloors": "TotalFloors_8",
            "Tenant": "Tenant_2",
            "WithinComplex": "WithinComplex_1",
            "WithinProximity": "WithinProximity_5",
            "Public": "Public_5",
            "Private": "Private_2",
            "NoofPassengerLift": "NoofPassengerLift_5",
            "CarParkLifttoG_F": "CarParkLifttoG_F_6",
            "ServiceLift": "ServiceLift_3",
            "CargoLift": "CargoLift_3",
            "NoofLiftZone": "NoofLiftZone_4",
            "CarParkLots": "CarParkLots_4",
            "AllocationRatio": "AllocationRatio_0",
            "UOM_AllocationRatio": "UOM_AllocationRatio_7",
            "ParkingDetails": "ParkingDetails_6",
            "Seasonal": "Seasonal_2",
            "Non_Reserved": "Non_Reserved_5",
            "MRT1": "MRT1_9",
            "MRT1CoveredAccess": "MRT1CoveredAccess_1",
            "MRT1Walk_Drive": "MRT1Walk_Drive_5",
            "MRT1Time_Mins": "MRT1Time_Mins_5",
            "MRT2": "MRT2_8",
            "MRT2CoveredAccess": "MRT2CoveredAccess_6",
            "MRT2Walk_Drive": "MRT2Walk_Drive_9",
            "MRT2Time_Mins_": "MRT2Time_Mins__7",
            "MRT3": "MRT3_4",
            "MRT3CoveredAccess": "MRT3CoveredAccess_4",
            "MRT3Walk_Drive": "MRT3Walk_Drive_8",
            "MRT3Time_Mins": "MRT3Time_Mins_3",
            "Bus": "Bus_8",
            "Others": "Others_4",
            "FloorToCeilingHeight_From": 1.32,
            "FloorToCeilingHeight_To": 7.27,
            "FloorLoadingRange_From": 6.93,
            "FloorLoadingRange_To": 2.4,
            "CeilingGrid_FloorLoadingDetails": "CeilingGrid_FloorLoadingDetails_3",
            "FloorSystem": "FloorSystem_8",
            "PowerSystem": "PowerSystem_4",
            "NoOfOfficeFloors": 1.68,
            "TypicalMinimumFloorSize": "TypicalMinimumFloorSize_3",
            "MaximumFloorSize_SqFt": "MaximumFloorSize_SqFt_9",
            "UltraHigh_TopFloor": "UltraHigh_TopFloor_2",
            "High_TopFloor": "undefined",
            "Mid_TopFloor": "undefined",
            "Low_TopFloor": "undefined",
            "TypeOfUse": "TypeOfUse_0",
            "NoOfLoadingBays": "NoOfLoadingBays_4",
            "AccessibleFor": "AccessibleFor_4",
            "Loading_UnloadingBay": "Loading_UnloadingBay_3",
            "NoOfCranes": "NoOfCranes_2",
            "OtherDetails": "OtherDetails_1",
            "NoOfRetailFloors": "NoOfRetailFloors_8",
            "Kind": "Kind_4",
            "AccountName": "AccountName_4",
            "Slug": "Slug_2",
            "Updated_at": "Updated_at_4",
            "Created_at": "Created_at_3",
            "Industry": "Industry_9"
         }
      ]
   }
},
"outJsonCascade" : {
   "name": "name_1",
   "Contry": "Contry_8",
   "lists": {
      "po_property_3D": [
         {
            "asset_class": "Commercial",
            "available_units": "yes",
            "floorplan_url": "floorplan_url_2",
            "image_url": "image_url_5",
            "ID": 2,
            "po_property_3D": {
               "ID": 3,
               "Name": "Name_5",
               "Grade": "undefined",
               "Country": "undefined",
               "PostalCode": "PostalCode_1",
               "Street_no": "Street_no_2",
               "Street": "Street_0",
               "Address": "Address_5",
               "Property_type": "Property_type_7",
               "Region": "undefined",
               "Micromarket": "undefined",
               "Zoning": "undefined",
               "Property_Usage": "undefined",
               "LandOwnership": "LandOwnership_9",
               "OwnershipStructure_Title": "undefined",
               "PropertyStatus": "PropertyStatus_1",
               "TOPDate": "7/16/2018, 21:51:00",
               "GrossFloorArea": 5.6,
               "LandArea": 3.23,
               "NetLettableArea": 1.6,
               "AreaBreakdown": "AreaBreakdown_4",
               "Headline": "Headline_5",
               "LocationDescription": "LocationDescription_0",
               "BuildingDescription": "BuildingDescription_8",
               "BelowGround": "BelowGround_5",
               "AboveGround": "AboveGround_7",
               "TotalFloors": "TotalFloors_4",
               "Tenant": "Tenant_0",
               "WithinComplex": "WithinComplex_7",
               "WithinProximity": "WithinProximity_9",
               "Public": "Public_9",
               "Private": "Private_0",
               "NoofPassengerLift": "NoofPassengerLift_4",
               "CarParkLifttoG_F": "CarParkLifttoG_F_5",
               "ServiceLift": "ServiceLift_3",
               "CargoLift": "CargoLift_5",
               "NoofLiftZone": "NoofLiftZone_9",
               "CarParkLots": "CarParkLots_1",
               "AllocationRatio": "AllocationRatio_1",
               "UOM_AllocationRatio": "UOM_AllocationRatio_6",
               "ParkingDetails": "ParkingDetails_3",
               "Seasonal": "Seasonal_8",
               "Non_Reserved": "Non_Reserved_3",
               "MRT1": "MRT1_2",
               "MRT1CoveredAccess": "MRT1CoveredAccess_5",
               "MRT1Walk_Drive": "MRT1Walk_Drive_2",
               "MRT1Time_Mins": "MRT1Time_Mins_7",
               "MRT2": "MRT2_8",
               "MRT2CoveredAccess": "MRT2CoveredAccess_1",
               "MRT2Walk_Drive": "MRT2Walk_Drive_4",
               "MRT2Time_Mins_": "MRT2Time_Mins__0",
               "MRT3": "MRT3_4",
               "MRT3CoveredAccess": "MRT3CoveredAccess_0",
               "MRT3Walk_Drive": "MRT3Walk_Drive_0",
               "MRT3Time_Mins": "MRT3Time_Mins_6",
               "Bus": "Bus_3",
               "Others": "Others_4",
               "FloorToCeilingHeight_From": 3.26,
               "FloorToCeilingHeight_To": 4.02,
               "FloorLoadingRange_From": 3.4,
               "FloorLoadingRange_To": 9.2,
               "CeilingGrid_FloorLoadingDetails": "CeilingGrid_FloorLoadingDetails_4",
               "FloorSystem": "FloorSystem_2",
               "PowerSystem": "PowerSystem_7",
               "NoOfOfficeFloors": 9.87,
               "TypicalMinimumFloorSize": "TypicalMinimumFloorSize_8",
               "MaximumFloorSize_SqFt": "MaximumFloorSize_SqFt_5",
               "UltraHigh_TopFloor": "UltraHigh_TopFloor_0",
               "High_TopFloor": "undefined",
               "Mid_TopFloor": "undefined",
               "Low_TopFloor": "undefined",
               "TypeOfUse": "TypeOfUse_1",
               "NoOfLoadingBays": "NoOfLoadingBays_4",
               "AccessibleFor": "AccessibleFor_7",
               "Loading_UnloadingBay": "Loading_UnloadingBay_6",
               "NoOfCranes": "NoOfCranes_8",
               "OtherDetails": "OtherDetails_8",
               "NoOfRetailFloors": "NoOfRetailFloors_2",
               "Kind": "Kind_6",
               "AccountName": "AccountName_3",
               "Slug": "Slug_6",
               "Updated_at": "Updated_at_7",
               "Created_at": "Created_at_0",
               "Industry": "Industry_8"
            }
         },
         {
            "asset_class": "Residential",
            "available_units": "yes",
            "floorplan_url": "floorplan_url_6",
            "image_url": "image_url_0",
            "ID": 9,
            "po_property_3D": {
               "ID": 3,
               "Name": "Name_1",
               "Grade": "undefined",
               "Country": "undefined",
               "PostalCode": "PostalCode_5",
               "Street_no": "Street_no_4",
               "Street": "Street_3",
               "Address": "Address_4",
               "Property_type": "Property_type_2",
               "Region": "undefined",
               "Micromarket": "undefined",
               "Zoning": "undefined",
               "Property_Usage": "undefined",
               "LandOwnership": "LandOwnership_0",
               "OwnershipStructure_Title": "undefined",
               "PropertyStatus": "PropertyStatus_1",
               "TOPDate": "2/5/2017, 02:44:51",
               "GrossFloorArea": 5.59,
               "LandArea": 4.3,
               "NetLettableArea": 8.42,
               "AreaBreakdown": "AreaBreakdown_7",
               "Headline": "Headline_2",
               "LocationDescription": "LocationDescription_6",
               "BuildingDescription": "BuildingDescription_3",
               "BelowGround": "BelowGround_5",
               "AboveGround": "AboveGround_1",
               "TotalFloors": "TotalFloors_3",
               "Tenant": "Tenant_6",
               "WithinComplex": "WithinComplex_6",
               "WithinProximity": "WithinProximity_3",
               "Public": "Public_7",
               "Private": "Private_1",
               "NoofPassengerLift": "NoofPassengerLift_0",
               "CarParkLifttoG_F": "CarParkLifttoG_F_3",
               "ServiceLift": "ServiceLift_6",
               "CargoLift": "CargoLift_1",
               "NoofLiftZone": "NoofLiftZone_1",
               "CarParkLots": "CarParkLots_4",
               "AllocationRatio": "AllocationRatio_1",
               "UOM_AllocationRatio": "UOM_AllocationRatio_3",
               "ParkingDetails": "ParkingDetails_2",
               "Seasonal": "Seasonal_1",
               "Non_Reserved": "Non_Reserved_2",
               "MRT1": "MRT1_4",
               "MRT1CoveredAccess": "MRT1CoveredAccess_5",
               "MRT1Walk_Drive": "MRT1Walk_Drive_1",
               "MRT1Time_Mins": "MRT1Time_Mins_2",
               "MRT2": "MRT2_8",
               "MRT2CoveredAccess": "MRT2CoveredAccess_5",
               "MRT2Walk_Drive": "MRT2Walk_Drive_5",
               "MRT2Time_Mins_": "MRT2Time_Mins__3",
               "MRT3": "MRT3_7",
               "MRT3CoveredAccess": "MRT3CoveredAccess_5",
               "MRT3Walk_Drive": "MRT3Walk_Drive_2",
               "MRT3Time_Mins": "MRT3Time_Mins_0",
               "Bus": "Bus_2",
               "Others": "Others_6",
               "FloorToCeilingHeight_From": 1.77,
               "FloorToCeilingHeight_To": 1.26,
               "FloorLoadingRange_From": 4.1,
               "FloorLoadingRange_To": 7.22,
               "CeilingGrid_FloorLoadingDetails": "CeilingGrid_FloorLoadingDetails_2",
               "FloorSystem": "FloorSystem_9",
               "PowerSystem": "PowerSystem_9",
               "NoOfOfficeFloors": 1.95,
               "TypicalMinimumFloorSize": "TypicalMinimumFloorSize_2",
               "MaximumFloorSize_SqFt": "MaximumFloorSize_SqFt_8",
               "UltraHigh_TopFloor": "UltraHigh_TopFloor_1",
               "High_TopFloor": "undefined",
               "Mid_TopFloor": "undefined",
               "Low_TopFloor": "undefined",
               "TypeOfUse": "TypeOfUse_9",
               "NoOfLoadingBays": "NoOfLoadingBays_7",
               "AccessibleFor": "AccessibleFor_5",
               "Loading_UnloadingBay": "Loading_UnloadingBay_5",
               "NoOfCranes": "NoOfCranes_6",
               "OtherDetails": "OtherDetails_6",
               "NoOfRetailFloors": "NoOfRetailFloors_5",
               "Kind": "Kind_8",
               "AccountName": "AccountName_4",
               "Slug": "Slug_6",
               "Updated_at": "Updated_at_1",
               "Created_at": "Created_at_1",
               "Industry": "Industry_4"
            }
         },
         {
            "asset_class": "Commercial",
            "available_units": "no",
            "floorplan_url": "floorplan_url_6",
            "image_url": "image_url_5",
            "ID": 6,
            "po_property_3D": {
               "ID": 2,
               "Name": "Name_7",
               "Grade": "undefined",
               "Country": "undefined",
               "PostalCode": "PostalCode_2",
               "Street_no": "Street_no_5",
               "Street": "Street_2",
               "Address": "Address_9",
               "Property_type": "Property_type_6",
               "Region": "undefined",
               "Micromarket": "undefined",
               "Zoning": "undefined",
               "Property_Usage": "undefined",
               "LandOwnership": "LandOwnership_9",
               "OwnershipStructure_Title": "undefined",
               "PropertyStatus": "PropertyStatus_4",
               "TOPDate": "10/27/2021, 17:40:55",
               "GrossFloorArea": 8.13,
               "LandArea": 9.16,
               "NetLettableArea": 3.59,
               "AreaBreakdown": "AreaBreakdown_7",
               "Headline": "Headline_7",
               "LocationDescription": "LocationDescription_5",
               "BuildingDescription": "BuildingDescription_0",
               "BelowGround": "BelowGround_3",
               "AboveGround": "AboveGround_1",
               "TotalFloors": "TotalFloors_3",
               "Tenant": "Tenant_2",
               "WithinComplex": "WithinComplex_7",
               "WithinProximity": "WithinProximity_4",
               "Public": "Public_7",
               "Private": "Private_8",
               "NoofPassengerLift": "NoofPassengerLift_4",
               "CarParkLifttoG_F": "CarParkLifttoG_F_6",
               "ServiceLift": "ServiceLift_5",
               "CargoLift": "CargoLift_6",
               "NoofLiftZone": "NoofLiftZone_4",
               "CarParkLots": "CarParkLots_0",
               "AllocationRatio": "AllocationRatio_3",
               "UOM_AllocationRatio": "UOM_AllocationRatio_9",
               "ParkingDetails": "ParkingDetails_5",
               "Seasonal": "Seasonal_6",
               "Non_Reserved": "Non_Reserved_2",
               "MRT1": "MRT1_0",
               "MRT1CoveredAccess": "MRT1CoveredAccess_1",
               "MRT1Walk_Drive": "MRT1Walk_Drive_4",
               "MRT1Time_Mins": "MRT1Time_Mins_8",
               "MRT2": "MRT2_4",
               "MRT2CoveredAccess": "MRT2CoveredAccess_2",
               "MRT2Walk_Drive": "MRT2Walk_Drive_1",
               "MRT2Time_Mins_": "MRT2Time_Mins__5",
               "MRT3": "MRT3_1",
               "MRT3CoveredAccess": "MRT3CoveredAccess_9",
               "MRT3Walk_Drive": "MRT3Walk_Drive_3",
               "MRT3Time_Mins": "MRT3Time_Mins_8",
               "Bus": "Bus_3",
               "Others": "Others_5",
               "FloorToCeilingHeight_From": 7.2,
               "FloorToCeilingHeight_To": 3.38,
               "FloorLoadingRange_From": 6.98,
               "FloorLoadingRange_To": 6.63,
               "CeilingGrid_FloorLoadingDetails": "CeilingGrid_FloorLoadingDetails_8",
               "FloorSystem": "FloorSystem_2",
               "PowerSystem": "PowerSystem_5",
               "NoOfOfficeFloors": 2.11,
               "TypicalMinimumFloorSize": "TypicalMinimumFloorSize_2",
               "MaximumFloorSize_SqFt": "MaximumFloorSize_SqFt_1",
               "UltraHigh_TopFloor": "UltraHigh_TopFloor_6",
               "High_TopFloor": "undefined",
               "Mid_TopFloor": "undefined",
               "Low_TopFloor": "undefined",
               "TypeOfUse": "TypeOfUse_2",
               "NoOfLoadingBays": "NoOfLoadingBays_2",
               "AccessibleFor": "AccessibleFor_0",
               "Loading_UnloadingBay": "Loading_UnloadingBay_1",
               "NoOfCranes": "NoOfCranes_8",
               "OtherDetails": "OtherDetails_5",
               "NoOfRetailFloors": "NoOfRetailFloors_1",
               "Kind": "Kind_0",
               "AccountName": "AccountName_0",
               "Slug": "Slug_3",
               "Updated_at": "Updated_at_7",
               "Created_at": "Created_at_0",
               "Industry": "Industry_2"
            }
         },
         {
            "asset_class": "Office",
            "available_units": "no",
            "floorplan_url": "floorplan_url_7",
            "image_url": "image_url_2",
            "ID": 7,
            "po_property_3D": {
               "ID": 2,
               "Name": "Name_6",
               "Grade": "undefined",
               "Country": "undefined",
               "PostalCode": "PostalCode_8",
               "Street_no": "Street_no_8",
               "Street": "Street_8",
               "Address": "Address_3",
               "Property_type": "Property_type_0",
               "Region": "undefined",
               "Micromarket": "undefined",
               "Zoning": "undefined",
               "Property_Usage": "undefined",
               "LandOwnership": "LandOwnership_9",
               "OwnershipStructure_Title": "undefined",
               "PropertyStatus": "PropertyStatus_9",
               "TOPDate": "1/17/2017, 24:58:54",
               "GrossFloorArea": 1,
               "LandArea": 9.68,
               "NetLettableArea": 8.88,
               "AreaBreakdown": "AreaBreakdown_8",
               "Headline": "Headline_8",
               "LocationDescription": "LocationDescription_0",
               "BuildingDescription": "BuildingDescription_9",
               "BelowGround": "BelowGround_3",
               "AboveGround": "AboveGround_1",
               "TotalFloors": "TotalFloors_2",
               "Tenant": "Tenant_5",
               "WithinComplex": "WithinComplex_6",
               "WithinProximity": "WithinProximity_3",
               "Public": "Public_5",
               "Private": "Private_8",
               "NoofPassengerLift": "NoofPassengerLift_8",
               "CarParkLifttoG_F": "CarParkLifttoG_F_4",
               "ServiceLift": "ServiceLift_0",
               "CargoLift": "CargoLift_0",
               "NoofLiftZone": "NoofLiftZone_4",
               "CarParkLots": "CarParkLots_2",
               "AllocationRatio": "AllocationRatio_9",
               "UOM_AllocationRatio": "UOM_AllocationRatio_6",
               "ParkingDetails": "ParkingDetails_4",
               "Seasonal": "Seasonal_3",
               "Non_Reserved": "Non_Reserved_1",
               "MRT1": "MRT1_9",
               "MRT1CoveredAccess": "MRT1CoveredAccess_0",
               "MRT1Walk_Drive": "MRT1Walk_Drive_7",
               "MRT1Time_Mins": "MRT1Time_Mins_3",
               "MRT2": "MRT2_6",
               "MRT2CoveredAccess": "MRT2CoveredAccess_1",
               "MRT2Walk_Drive": "MRT2Walk_Drive_4",
               "MRT2Time_Mins_": "MRT2Time_Mins__3",
               "MRT3": "MRT3_5",
               "MRT3CoveredAccess": "MRT3CoveredAccess_1",
               "MRT3Walk_Drive": "MRT3Walk_Drive_8",
               "MRT3Time_Mins": "MRT3Time_Mins_2",
               "Bus": "Bus_7",
               "Others": "Others_7",
               "FloorToCeilingHeight_From": 6.47,
               "FloorToCeilingHeight_To": 3.31,
               "FloorLoadingRange_From": 9.49,
               "FloorLoadingRange_To": 6.81,
               "CeilingGrid_FloorLoadingDetails": "CeilingGrid_FloorLoadingDetails_8",
               "FloorSystem": "FloorSystem_3",
               "PowerSystem": "PowerSystem_0",
               "NoOfOfficeFloors": 6.55,
               "TypicalMinimumFloorSize": "TypicalMinimumFloorSize_5",
               "MaximumFloorSize_SqFt": "MaximumFloorSize_SqFt_3",
               "UltraHigh_TopFloor": "UltraHigh_TopFloor_8",
               "High_TopFloor": "undefined",
               "Mid_TopFloor": "undefined",
               "Low_TopFloor": "undefined",
               "TypeOfUse": "TypeOfUse_4",
               "NoOfLoadingBays": "NoOfLoadingBays_4",
               "AccessibleFor": "AccessibleFor_3",
               "Loading_UnloadingBay": "Loading_UnloadingBay_6",
               "NoOfCranes": "NoOfCranes_5",
               "OtherDetails": "OtherDetails_0",
               "NoOfRetailFloors": "NoOfRetailFloors_2",
               "Kind": "Kind_5",
               "AccountName": "AccountName_8",
               "Slug": "Slug_5",
               "Updated_at": "Updated_at_0",
               "Created_at": "Created_at_6",
               "Industry": "Industry_7"
            }
         },
         {
            "asset_class": "Commercial",
            "available_units": "no",
            "floorplan_url": "floorplan_url_0",
            "image_url": "image_url_8",
            "ID": 3,
            "po_property_3D": {
               "ID": 4,
               "Name": "Name_7",
               "Grade": "undefined",
               "Country": "undefined",
               "PostalCode": "PostalCode_4",
               "Street_no": "Street_no_2",
               "Street": "Street_8",
               "Address": "Address_4",
               "Property_type": "Property_type_1",
               "Region": "undefined",
               "Micromarket": "undefined",
               "Zoning": "undefined",
               "Property_Usage": "undefined",
               "LandOwnership": "LandOwnership_4",
               "OwnershipStructure_Title": "undefined",
               "PropertyStatus": "PropertyStatus_9",
               "TOPDate": "10/4/2020, 05:26:59",
               "GrossFloorArea": 1.14,
               "LandArea": 6.69,
               "NetLettableArea": 8.12,
               "AreaBreakdown": "AreaBreakdown_1",
               "Headline": "Headline_2",
               "LocationDescription": "LocationDescription_4",
               "BuildingDescription": "BuildingDescription_9",
               "BelowGround": "BelowGround_9",
               "AboveGround": "AboveGround_1",
               "TotalFloors": "TotalFloors_0",
               "Tenant": "Tenant_0",
               "WithinComplex": "WithinComplex_7",
               "WithinProximity": "WithinProximity_7",
               "Public": "Public_0",
               "Private": "Private_5",
               "NoofPassengerLift": "NoofPassengerLift_1",
               "CarParkLifttoG_F": "CarParkLifttoG_F_5",
               "ServiceLift": "ServiceLift_0",
               "CargoLift": "CargoLift_5",
               "NoofLiftZone": "NoofLiftZone_0",
               "CarParkLots": "CarParkLots_5",
               "AllocationRatio": "AllocationRatio_7",
               "UOM_AllocationRatio": "UOM_AllocationRatio_0",
               "ParkingDetails": "ParkingDetails_1",
               "Seasonal": "Seasonal_0",
               "Non_Reserved": "Non_Reserved_8",
               "MRT1": "MRT1_3",
               "MRT1CoveredAccess": "MRT1CoveredAccess_2",
               "MRT1Walk_Drive": "MRT1Walk_Drive_6",
               "MRT1Time_Mins": "MRT1Time_Mins_3",
               "MRT2": "MRT2_6",
               "MRT2CoveredAccess": "MRT2CoveredAccess_6",
               "MRT2Walk_Drive": "MRT2Walk_Drive_1",
               "MRT2Time_Mins_": "MRT2Time_Mins__2",
               "MRT3": "MRT3_3",
               "MRT3CoveredAccess": "MRT3CoveredAccess_5",
               "MRT3Walk_Drive": "MRT3Walk_Drive_1",
               "MRT3Time_Mins": "MRT3Time_Mins_3",
               "Bus": "Bus_9",
               "Others": "Others_7",
               "FloorToCeilingHeight_From": 7.12,
               "FloorToCeilingHeight_To": 7.94,
               "FloorLoadingRange_From": 5.48,
               "FloorLoadingRange_To": 1.51,
               "CeilingGrid_FloorLoadingDetails": "CeilingGrid_FloorLoadingDetails_9",
               "FloorSystem": "FloorSystem_0",
               "PowerSystem": "PowerSystem_5",
               "NoOfOfficeFloors": 7.97,
               "TypicalMinimumFloorSize": "TypicalMinimumFloorSize_2",
               "MaximumFloorSize_SqFt": "MaximumFloorSize_SqFt_9",
               "UltraHigh_TopFloor": "UltraHigh_TopFloor_6",
               "High_TopFloor": "undefined",
               "Mid_TopFloor": "undefined",
               "Low_TopFloor": "undefined",
               "TypeOfUse": "TypeOfUse_0",
               "NoOfLoadingBays": "NoOfLoadingBays_4",
               "AccessibleFor": "AccessibleFor_5",
               "Loading_UnloadingBay": "Loading_UnloadingBay_1",
               "NoOfCranes": "NoOfCranes_8",
               "OtherDetails": "OtherDetails_0",
               "NoOfRetailFloors": "NoOfRetailFloors_2",
               "Kind": "Kind_1",
               "AccountName": "AccountName_2",
               "Slug": "Slug_7",
               "Updated_at": "Updated_at_1",
               "Created_at": "Created_at_6",
               "Industry": "Industry_9"
            }
         }
      ]
   }
}
}